name: Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BuildConfiguration: debug

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test -c ${{env.BuildConfiguration}} --no-restore -l trx
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Dotnet Tests            # Name of the check run which will be created
        path: '**/TestResults/*.trx'    # Path to test results
        reporter: dotnet-trx

    - name: Pack
      run: |
        dotnet pack -c ${{env.BuildConfiguration}} --no-restore PhoenixToolkits.Authorization.Abstractions/PhoenixToolkits.Authorization.Abstractions.csproj
        dotnet pack -c ${{env.BuildConfiguration}} --no-restore PhoenixToolkits.Authorization.AspNetCore/PhoenixToolkits.Authorization.AspNetCore.csproj

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: nuget
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          PhoenixToolkits.Authorization.Abstractions/bin/${{env.BuildConfiguration}}/*.nupkg
          PhoenixToolkits.Authorization.AspNetCore/bin/${{env.BuildConfiguration}}/*.nupkg

  push-nuget-package:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        # Artifact name
        name: nuget
        # Destination path
        path: nuget

    - name: push
      run: |
        dotnet nuget push "nuget\*.nupkg" -s "nuget.org" -k "${{ secrets.NUGETAPIKEY }}" --skip-duplicate